"""Initial production schema, explicit and reproducible.

Revision ID: 0001_initial
"""
from alembic import op
import sqlalchemy as sa

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_actor_timestamp', 'audit_logs', ['actor', 'timestamp'], unique=False)
    op.create_index('ix_audit_entity_timestamp', 'audit_logs', ['entity_type', 'entity_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor'), 'audit_logs', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('input_type', sa.String(length=30), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('input_payload', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=True),
    sa.Column('workflow_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("workflow_status IN ('RECEIVED','PROCESSING','NEED_REVIEW','COMPLETED','FAILED')", name='ck_case_workflow_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('created_by', 'idempotency_key', name='uq_case_actor_idempotency')
    )
    op.create_index(op.f('ix_cases_created_at'), 'cases', ['created_at'], unique=False)
    op.create_index(op.f('ix_cases_created_by'), 'cases', ['created_by'], unique=False)
    op.create_index(op.f('ix_cases_workflow_status'), 'cases', ['workflow_status'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('aggregate_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_id', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.CheckConstraint("status IN ('PENDING','SENT','FAILED')", name='ck_outbox_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_events_aggregate_id'), 'outbox_events', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_event_type'), 'outbox_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_outbox_events_status'), 'outbox_events', ['status'], unique=False)
    op.create_index('ix_outbox_status_available', 'outbox_events', ['status', 'available_at'], unique=False)
    op.create_table('policy_rules',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('policy_type', sa.String(length=100), nullable=False),
    sa.Column('subject_groups', sa.JSON(), nullable=False),
    sa.Column('required_fields', sa.JSON(), nullable=False),
    sa.Column('rule_expression', sa.JSON(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('policy_version', sa.String(length=100), nullable=False),
    sa.Column('source_kind', sa.String(length=30), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("source_kind IN ('OFFICIAL','PROVIDED','SYNTHETIC_DEMO')", name='ck_policy_source_kind'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_rules_active'), 'policy_rules', ['active'], unique=False)
    op.create_index(op.f('ix_policy_rules_policy_version'), 'policy_rules', ['policy_version'], unique=False)
    op.create_table('registry_versions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('DRAFT','VALIDATED','APPROVED','PUBLISHED','DEPRECATED')", name='ck_registry_version_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registry_versions_created_at'), 'registry_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_registry_versions_status'), 'registry_versions', ['status'], unique=False)
    op.create_index(op.f('ix_registry_versions_version'), 'registry_versions', ['version'], unique=True)
    op.create_index('uq_registry_single_published', 'registry_versions', ['status'], unique=True, postgresql_where=sa.text("status = 'PUBLISHED'"), sqlite_where=sa.text("status = 'PUBLISHED'"))
    op.create_table('sources',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('authority', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('source_kind', sa.String(length=30), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.CheckConstraint("source_kind IN ('OFFICIAL','PROVIDED','SYNTHETIC_DEMO')", name='ck_source_kind'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_source_kind'), 'sources', ['source_kind'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=150), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=False),
    sa.Column('parse_status', sa.String(length=30), nullable=False),
    sa.Column('parse_confidence', sa.Float(), nullable=True),
    sa.CheckConstraint("parse_status IN ('PENDING','PARSED','FAILED')", name='ck_document_parse_status'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_case_id'), 'documents', ['case_id'], unique=False)
    op.create_index(op.f('ix_documents_checksum'), 'documents', ['checksum'], unique=False)
    op.create_index(op.f('ix_documents_parse_status'), 'documents', ['parse_status'], unique=False)
    op.create_table('registry_candidates',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('raw_name', sa.String(length=1000), nullable=False),
    sa.Column('proposed_name', sa.String(length=500), nullable=False),
    sa.Column('normalized_key', sa.String(length=500), nullable=False),
    sa.Column('organization_type', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('PENDING_QA','APPROVED','REJECTED')", name='ck_registry_candidate_status'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_registry_candidate_status_created', 'registry_candidates', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_registry_candidates_created_at'), 'registry_candidates', ['created_at'], unique=False)
    op.create_index(op.f('ix_registry_candidates_normalized_key'), 'registry_candidates', ['normalized_key'], unique=False)
    op.create_index(op.f('ix_registry_candidates_status'), 'registry_candidates', ['status'], unique=False)
    op.create_table('units',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('canonical_name', sa.String(length=500), nullable=False),
    sa.Column('normalized_key', sa.String(length=500), nullable=False),
    sa.Column('organization_type', sa.String(length=20), nullable=False),
    sa.Column('unit_level', sa.String(length=80), nullable=True),
    sa.Column('coverage_group', sa.String(length=120), nullable=True),
    sa.Column('parent_unit_id', sa.String(length=64), nullable=True),
    sa.Column('qa_status', sa.String(length=30), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('registry_version_id', sa.String(length=64), nullable=True),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("organization_type IN ('BCA','BQP','OTHER','UNKNOWN')", name='ck_unit_org'),
    sa.CheckConstraint("qa_status IN ('PENDING_QA','APPROVED','REJECTED')", name='ck_unit_qa'),
    sa.CheckConstraint('valid_to IS NULL OR valid_from IS NULL OR valid_from <= valid_to', name='ck_unit_validity'),
    sa.ForeignKeyConstraint(['parent_unit_id'], ['units.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['registry_version_id'], ['registry_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_units_active'), 'units', ['active'], unique=False)
    op.create_index('ix_units_active_qa', 'units', ['active', 'qa_status'], unique=False)
    op.create_index(op.f('ix_units_canonical_name'), 'units', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_units_coverage_group'), 'units', ['coverage_group'], unique=False)
    op.create_index(op.f('ix_units_normalized_key'), 'units', ['normalized_key'], unique=False)
    op.create_index('ix_units_org_active_qa', 'units', ['organization_type', 'active', 'qa_status'], unique=False)
    op.create_index(op.f('ix_units_organization_type'), 'units', ['organization_type'], unique=False)
    op.create_index(op.f('ix_units_qa_status'), 'units', ['qa_status'], unique=False)
    op.create_table('extracted_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=True),
    sa.Column('subject_name', sa.String(length=300), nullable=True),
    sa.Column('subject_code', sa.String(length=160), nullable=True),
    sa.Column('position', sa.String(length=300), nullable=True),
    sa.Column('current_unit_raw', sa.String(length=1000), nullable=True),
    sa.Column('former_units', sa.JSON(), nullable=False),
    sa.Column('extracted_fields', sa.JSON(), nullable=False),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('relation_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_records_case_id'), 'extracted_records', ['case_id'], unique=False)
    op.create_table('registry_snapshot_units',
    sa.Column('registry_version_id', sa.String(length=64), nullable=False),
    sa.Column('unit_id', sa.String(length=64), nullable=False),
    sa.Column('canonical_name', sa.String(length=500), nullable=False),
    sa.Column('normalized_key', sa.String(length=500), nullable=False),
    sa.Column('organization_type', sa.String(length=20), nullable=False),
    sa.Column('unit_level', sa.String(length=80), nullable=True),
    sa.Column('coverage_group', sa.String(length=120), nullable=True),
    sa.Column('parent_unit_id', sa.String(length=64), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('included_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['registry_version_id'], ['registry_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('registry_version_id', 'unit_id')
    )
    op.create_index('ix_snapshot_unit_version_normalized', 'registry_snapshot_units', ['registry_version_id', 'normalized_key'], unique=False)
    op.create_index('ix_snapshot_unit_version_org', 'registry_snapshot_units', ['registry_version_id', 'organization_type'], unique=False)
    op.create_table('unit_codes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('unit_id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=160), nullable=False),
    sa.Column('code_type', sa.String(length=80), nullable=False),
    sa.Column('namespace', sa.String(length=80), nullable=False),
    sa.Column('qa_status', sa.String(length=30), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.CheckConstraint("qa_status IN ('PENDING_QA','APPROVED','REJECTED')", name='ck_unit_code_qa'),
    sa.CheckConstraint('valid_to IS NULL OR valid_from IS NULL OR valid_from <= valid_to', name='ck_unit_code_validity'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'namespace', name='uq_unit_code_namespace')
    )
    op.create_index(op.f('ix_unit_codes_code'), 'unit_codes', ['code'], unique=False)
    op.create_index(op.f('ix_unit_codes_qa_status'), 'unit_codes', ['qa_status'], unique=False)
    op.create_index(op.f('ix_unit_codes_unit_id'), 'unit_codes', ['unit_id'], unique=False)
    op.create_table('unit_names',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('unit_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('normalized_key', sa.String(length=500), nullable=False),
    sa.Column('name_type', sa.String(length=30), nullable=False),
    sa.Column('qa_status', sa.String(length=30), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.CheckConstraint("qa_status IN ('PENDING_QA','APPROVED','REJECTED')", name='ck_unit_name_qa'),
    sa.CheckConstraint('valid_to IS NULL OR valid_from IS NULL OR valid_from <= valid_to', name='ck_unit_name_validity'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id', 'normalized_key', 'name_type', name='uq_unit_name')
    )
    op.create_index(op.f('ix_unit_names_normalized_key'), 'unit_names', ['normalized_key'], unique=False)
    op.create_index(op.f('ix_unit_names_qa_status'), 'unit_names', ['qa_status'], unique=False)
    op.create_index(op.f('ix_unit_names_unit_id'), 'unit_names', ['unit_id'], unique=False)
    op.create_table('verification_results',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('unit_id', sa.String(length=64), nullable=True),
    sa.Column('organization_type', sa.String(length=20), nullable=False),
    sa.Column('resolution_status', sa.String(length=30), nullable=False),
    sa.Column('subject_group', sa.String(length=100), nullable=True),
    sa.Column('match_method', sa.String(length=50), nullable=True),
    sa.Column('resolution_score', sa.Float(), nullable=True),
    sa.Column('candidate_margin', sa.Float(), nullable=True),
    sa.Column('decision_confidence', sa.Float(), nullable=True),
    sa.Column('top_candidates', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('source_kind', sa.String(length=30), nullable=False),
    sa.Column('registry_version', sa.String(length=100), nullable=True),
    sa.Column('taxonomy_version', sa.String(length=100), nullable=False),
    sa.Column('parser_version', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('threshold_version', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("organization_type IN ('BCA','BQP','OTHER','UNKNOWN')", name='ck_result_org'),
    sa.CheckConstraint("resolution_status IN ('MATCHED','AMBIGUOUS','NOT_FOUND','CONFLICT')", name='ck_result_resolution'),
    sa.CheckConstraint("source_kind IN ('OFFICIAL','PROVIDED','SYNTHETIC_DEMO')", name='ck_result_source_kind'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_results_case_id'), 'verification_results', ['case_id'], unique=True)
    op.create_table('eligibility_assessments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('result_id', sa.String(length=64), nullable=False),
    sa.Column('policy_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('policy_version', sa.String(length=100), nullable=False),
    sa.Column('source_kind', sa.String(length=30), nullable=False),
    sa.CheckConstraint("source_kind IN ('OFFICIAL','PROVIDED','SYNTHETIC_DEMO')", name='ck_eligibility_source_kind'),
    sa.CheckConstraint("status IN ('ELIGIBLE','NOT_ELIGIBLE','INSUFFICIENT_DATA','NOT_APPLICABLE')", name='ck_eligibility_status'),
    sa.ForeignKeyConstraint(['policy_id'], ['policy_rules.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['result_id'], ['verification_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('result_id', 'policy_id', name='uq_assessment_result_policy')
    )
    op.create_index(op.f('ix_eligibility_assessments_policy_id'), 'eligibility_assessments', ['policy_id'], unique=False)
    op.create_index(op.f('ix_eligibility_assessments_result_id'), 'eligibility_assessments', ['result_id'], unique=False)
    op.create_table('registry_snapshot_codes',
    sa.Column('registry_version_id', sa.String(length=64), nullable=False),
    sa.Column('unit_code_id', sa.String(length=64), nullable=False),
    sa.Column('unit_id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=160), nullable=False),
    sa.Column('code_type', sa.String(length=80), nullable=False),
    sa.Column('namespace', sa.String(length=80), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('included_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['registry_version_id'], ['registry_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_code_id'], ['unit_codes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('registry_version_id', 'unit_code_id')
    )
    op.create_index(op.f('ix_registry_snapshot_codes_unit_id'), 'registry_snapshot_codes', ['unit_id'], unique=False)
    op.create_index('ix_snapshot_code_version_code', 'registry_snapshot_codes', ['registry_version_id', 'code'], unique=False)
    op.create_table('registry_snapshot_names',
    sa.Column('registry_version_id', sa.String(length=64), nullable=False),
    sa.Column('unit_name_id', sa.String(length=64), nullable=False),
    sa.Column('unit_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('normalized_key', sa.String(length=500), nullable=False),
    sa.Column('name_type', sa.String(length=30), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('included_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['registry_version_id'], ['registry_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_name_id'], ['unit_names.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('registry_version_id', 'unit_name_id')
    )
    op.create_index(op.f('ix_registry_snapshot_names_unit_id'), 'registry_snapshot_names', ['unit_id'], unique=False)
    op.create_index('ix_snapshot_name_version_normalized', 'registry_snapshot_names', ['registry_version_id', 'normalized_key'], unique=False)
    op.create_table('review_cases',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('result_id', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('coverage_group', sa.String(length=120), nullable=True),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('OPEN','RESOLVED','DISMISSED')", name='ck_review_status'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['result_id'], ['verification_results.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_cases_assigned_to'), 'review_cases', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_review_cases_case_id'), 'review_cases', ['case_id'], unique=False)
    op.create_index(op.f('ix_review_cases_coverage_group'), 'review_cases', ['coverage_group'], unique=False)
    op.create_index(op.f('ix_review_cases_created_at'), 'review_cases', ['created_at'], unique=False)
    op.create_index(op.f('ix_review_cases_status'), 'review_cases', ['status'], unique=False)
    op.create_index('ix_review_scope_status', 'review_cases', ['coverage_group', 'status'], unique=False)
    op.create_index('ix_review_status_created', 'review_cases', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_review_status_created', table_name='review_cases')
    op.drop_index('ix_review_scope_status', table_name='review_cases')
    op.drop_index(op.f('ix_review_cases_status'), table_name='review_cases')
    op.drop_index(op.f('ix_review_cases_created_at'), table_name='review_cases')
    op.drop_index(op.f('ix_review_cases_coverage_group'), table_name='review_cases')
    op.drop_index(op.f('ix_review_cases_case_id'), table_name='review_cases')
    op.drop_index(op.f('ix_review_cases_assigned_to'), table_name='review_cases')
    op.drop_table('review_cases')
    op.drop_index('ix_snapshot_name_version_normalized', table_name='registry_snapshot_names')
    op.drop_index(op.f('ix_registry_snapshot_names_unit_id'), table_name='registry_snapshot_names')
    op.drop_table('registry_snapshot_names')
    op.drop_index('ix_snapshot_code_version_code', table_name='registry_snapshot_codes')
    op.drop_index(op.f('ix_registry_snapshot_codes_unit_id'), table_name='registry_snapshot_codes')
    op.drop_table('registry_snapshot_codes')
    op.drop_index(op.f('ix_eligibility_assessments_result_id'), table_name='eligibility_assessments')
    op.drop_index(op.f('ix_eligibility_assessments_policy_id'), table_name='eligibility_assessments')
    op.drop_table('eligibility_assessments')
    op.drop_index(op.f('ix_verification_results_case_id'), table_name='verification_results')
    op.drop_table('verification_results')
    op.drop_index(op.f('ix_unit_names_unit_id'), table_name='unit_names')
    op.drop_index(op.f('ix_unit_names_qa_status'), table_name='unit_names')
    op.drop_index(op.f('ix_unit_names_normalized_key'), table_name='unit_names')
    op.drop_table('unit_names')
    op.drop_index(op.f('ix_unit_codes_unit_id'), table_name='unit_codes')
    op.drop_index(op.f('ix_unit_codes_qa_status'), table_name='unit_codes')
    op.drop_index(op.f('ix_unit_codes_code'), table_name='unit_codes')
    op.drop_table('unit_codes')
    op.drop_index('ix_snapshot_unit_version_org', table_name='registry_snapshot_units')
    op.drop_index('ix_snapshot_unit_version_normalized', table_name='registry_snapshot_units')
    op.drop_table('registry_snapshot_units')
    op.drop_index(op.f('ix_extracted_records_case_id'), table_name='extracted_records')
    op.drop_table('extracted_records')
    op.drop_index(op.f('ix_units_qa_status'), table_name='units')
    op.drop_index(op.f('ix_units_organization_type'), table_name='units')
    op.drop_index('ix_units_org_active_qa', table_name='units')
    op.drop_index(op.f('ix_units_normalized_key'), table_name='units')
    op.drop_index(op.f('ix_units_coverage_group'), table_name='units')
    op.drop_index(op.f('ix_units_canonical_name'), table_name='units')
    op.drop_index('ix_units_active_qa', table_name='units')
    op.drop_index(op.f('ix_units_active'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_registry_candidates_status'), table_name='registry_candidates')
    op.drop_index(op.f('ix_registry_candidates_normalized_key'), table_name='registry_candidates')
    op.drop_index(op.f('ix_registry_candidates_created_at'), table_name='registry_candidates')
    op.drop_index('ix_registry_candidate_status_created', table_name='registry_candidates')
    op.drop_table('registry_candidates')
    op.drop_index(op.f('ix_documents_parse_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_checksum'), table_name='documents')
    op.drop_index(op.f('ix_documents_case_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_sources_source_kind'), table_name='sources')
    op.drop_table('sources')
    op.drop_index('uq_registry_single_published', table_name='registry_versions', postgresql_where=sa.text("status = 'PUBLISHED'"), sqlite_where=sa.text("status = 'PUBLISHED'"))
    op.drop_index(op.f('ix_registry_versions_version'), table_name='registry_versions')
    op.drop_index(op.f('ix_registry_versions_status'), table_name='registry_versions')
    op.drop_index(op.f('ix_registry_versions_created_at'), table_name='registry_versions')
    op.drop_table('registry_versions')
    op.drop_index(op.f('ix_policy_rules_policy_version'), table_name='policy_rules')
    op.drop_index(op.f('ix_policy_rules_active'), table_name='policy_rules')
    op.drop_table('policy_rules')
    op.drop_index('ix_outbox_status_available', table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_status'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_event_type'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_aggregate_id'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_cases_workflow_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_created_by'), table_name='cases')
    op.drop_index(op.f('ix_cases_created_at'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('ix_audit_entity_timestamp', table_name='audit_logs')
    op.drop_index('ix_audit_actor_timestamp', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
